global:
  copyright: © 2018 MFCare Jsc.
  site_title: MFCare
user:
  name_maximum_length: 50
  email_maximum_length: 255
  password_minimum_length: 6
  gravatar_size: 50
  password_reset_expired: 2
  gravatar_size_follow: 30
default:
  avatar: logo.png
  doctor_image: doctor_default.png
doctor:
  right_column: 0
admin:
  truncate_length: 50
  item_per_page: 10
  doctor:
    activate: activate
  block: block
  unblock: unblock
  per_page: 5
default_page: 1
default_load_more: 2
home:
  suggest_text_len: 100
  suggest_limit: 10
